import React from "react";

export default function PrivacyPolicy() {
  return (
    <div className="w-full bg-white">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 md:px-10 py-10 text-gray-800 leading-relaxed">

        <h1 className="text-3xl sm:text-4xl font-bold mb-2">
          Privacy Policy
        </h1>

        <p className="text-sm text-gray-500 mb-6">
          Last updated: January 02, 2026
        </p>

        <p>
          This Privacy Policy describes Our policies and procedures on the collection,
          use and disclosure of Your information when You use the Service and tells
          You about Your privacy rights and how the law protects You.
        </p>

        <p className="mt-4">
          We use Your Personal data to provide and improve the Service. By using the
          Service, You agree to the collection and use of information in accordance
          with this Privacy Policy. This Privacy Policy has been created with the help
          of the Privacy Policy Generator.
        </p>

        <h2 className="text-2xl font-semibold mt-10 mb-3">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Interpretation
        </h3>

        <p>
          The words whose initial letters are capitalized have meanings defined under
          the following conditions. The following definitions shall have the same
          meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Definitions
        </h3>

        <p className="mb-4">
          For the purposes of this Privacy Policy:
        </p>

        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party.</li>
          <li><strong>Company</strong> refers to Business Kerala, CUSAT Road, South Kalamassery, Ernakulam 682022.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Kerala, India.</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li>
            <strong>Website</strong> refers to Business Kerala, accessible from{" "}
            <a
              href="https://bkfinder.com/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 underline break-all"
            >
              https://bkfinder.com/
            </a>
          </li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-10 mb-3">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Types of Data Collected
        </h3>

        <h4 className="text-lg font-semibold mt-4 mb-2">
          Personal Data
        </h4>

        <p>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>

        <ul className="list-disc pl-6 mt-3 space-y-1">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-semibold mt-6 mb-2">
          Usage Data
        </h4>

        <p>
         Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>

        <p className="mt-4">
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>

        <p className="mt-4">
            We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
        </p>

        <h3 className="text-xl font-semibold mt-10 mb-2">
          Tracking Technologies and Cookies
        </h3>

        <p>
         We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
        </p>

        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li> <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
          <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>

        <p className="mt-4">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.</p>

        <p className="mt-4">We use both Session and Persistent Cookies for the purposes set out below:</p>

         <ul className="list-disc pl-6 mt-3 space-y-2">
            <li><strong>Necessary / Essential Cookies</strong></li>
            <p>Type: Session Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            <li><strong>Cookies Policy / Notice Acceptance Cookies</strong></li>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            <li><strong>Functionality Cookies</strong></li>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
         </ul>

         <p className="mt-4">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

        <h3 className="text-xl font-semibold mt-10 mb-2">
          Use of Your Personal Data
        </h3>

        <p className="mb-3">The Company may use Personal Data for the following purposes:</p>

        <ul className="list-disc pl-6 space-y-2">
          <li><strong>To provide and maintain the Service, </strong>including to monitor the usage of our Service</li>
          <li><strong>To manage Your account and registrations: </strong>to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
          <li><strong>To contact You: </strong>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.

</li>
          <li><strong>To provide You </strong>with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
          <li><strong>To manage Your requests: </strong>To attend and manage Your requests to Us.

</li>

<li><strong>For business transfers: </strong>We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
<li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
        </ul>


        <h3 className="text-xl font-semibold mt-10 mb-2">
          Retention of Your Personal Data
        </h3>

        <p>
         The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
</p>
<p className="mt-4">
The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.
        </p>

        <h3 className="text-xl font-semibold mt-10 mb-2">
          Security of Your Personal Data
        </h3>

        <p>
         The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.


          the Internet is 100% secure.
        </p>

        <h3 className="text-xl font-semibold mt-10 mb-2">
          Children's Privacy
        </h3>

        <p className="mb-4">
         Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
</p>
<p>
If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.


        </p>

        <h3 className="text-xl font-semibold mt-10 mb-2">
          Changes to this Privacy Policy
        </h3>

        <p >
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="mt-4">
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
        </p>
        <p className="mt-4">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>

        <h3 className="text-xl font-semibold mt-10 mb-2">
          Contact Us
        </h3>

        <div className="mt-3 space-y-2">
          <p>
            📧 Email:{" "}
            <a
              href="mailto:businesskeralagroup@gmail.com"
              className="text-blue-600 underline break-all"
            >
              businesskeralagroup@gmail.com
            </a>
          </p>

          <p>
            🌐 Website:{" "}
            <a
              href="https://businesskerala.org/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 underline break-all"
            >
              https://businesskerala.org/
            </a>
          </p>

          <p>
            📞 Phone:{" "}
            <a
              href="tel:+917511194200"
              className="text-blue-600 underline"
            >
              +91 75 111 94 200
            </a>
          </p>
        </div>

      </div>
    </div>
  );
}