import React from "react";

function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white text-gray-900 px-4 py-10 sm:px-8 lg:px-16">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-2xl sm:text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-xs sm:text-sm text-gray-500 mb-6">
          Last updated: January 02, 2026
        </p>

        <p className="text-sm sm:text-base text-gray-700 mb-4">
          This Privacy Policy describes our policies and procedures on the
          collection, use and disclosure of your information when you use the
          Service and tells you about your privacy rights and how the law protects
          you.
        </p>

        <p className="text-sm sm:text-base text-gray-700 mb-4">
          We use your personal data to provide and improve the Service. By using
          the Service, you agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Interpretation and Definitions
        </h2>

        <h3 className="text-base sm:text-lg font-semibold mt-4 mb-2">Interpretation</h3>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. The following definitions shall have the
          same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-base sm:text-lg font-semibold mt-4 mb-2">Definitions</h3>
        <p className="text-sm sm:text-base text-gray-700 mb-3">
          For the purposes of this Privacy Policy:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base text-gray-700 mb-4">
          <li>
            <span className="font-semibold">Account</span> means a unique account
            created for you to access our Service or parts of our Service.
          </li>
          <li>
            <span className="font-semibold">Affiliate</span> means an entity that
            controls, is controlled by, or is under common control with a party.
          </li>
          <li>
            <span className="font-semibold">Company</span> refers to Business
            Kerala, CUSAT Road, South Kalamassery, Ernakulam 682022.
          </li>
          <li>
            <span className="font-semibold">Cookies</span> are small files that
            are placed on your computer, mobile device or any other device by a
            website, containing the details of your browsing history on that
            website among its many uses.
          </li>
          <li>
            <span className="font-semibold">Country</span> refers to Kerala,
            India.
          </li>
          <li>
            <span className="font-semibold">Device</span> means any device that
            can access the Service such as a computer, a cell phone or a digital
            tablet.
          </li>
          <li>
            <span className="font-semibold">Personal Data</span> is any
            information that relates to an identifiable individual.
          </li>
          <li>
            <span className="font-semibold">Service</span> refers to the
            Website.
          </li>
          <li>
            <span className="font-semibold">Service Provider</span> means any
            natural or legal person who processes the data on behalf of the
            Company. It refers to third-party companies or individuals employed by
            the Company to facilitate the Service, to provide the Service on
            behalf of the Company, to perform services related to the Service or
            to assist the Company in analyzing how the Service is used.
          </li>
          <li>
            <span className="font-semibold">Usage Data</span> refers to data
            collected automatically, either generated by the use of the Service or
            from the Service infrastructure itself (for example, the duration of a
            page visit).
          </li>
          <li>
            <span className="font-semibold">Website</span> refers to Business
            Kerala, accessible from
            <span className="ml-1">https://bkfinder.com/</span>
          </li>
          <li>
            <span className="font-semibold">You</span> means the individual
            accessing or using the Service, or the company or other legal entity
            on behalf of which such individual is accessing or using the Service,
            as applicable.
          </li>
        </ul>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-base sm:text-lg font-semibold mt-4 mb-2">
          Types of Data Collected
        </h3>
        <h4 className="text-sm sm:text-base font-semibold mt-2 mb-2">
          Personal Data
        </h4>
        <p className="text-sm sm:text-base text-gray-700 mb-3">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is not
          limited to:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-sm sm:text-base text-gray-700 mb-4">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-sm sm:text-base font-semibold mt-4 mb-2">
          Usage Data
        </h4>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          Usage Data may include information such as your device&apos;s Internet
          Protocol address (IP address), browser type, browser version, the pages
          of our Service that you visit, the time and date of your visit, the time
          spent on those pages, unique device identifiers and other diagnostic
          data. When you access the Service by or through a mobile device, we may
          collect certain information automatically, including, but not limited
          to, the type of mobile device you use, your mobile device&apos;s unique ID,
          the IP address of your mobile device, your mobile operating system, the
          type of mobile Internet browser you use, unique device identifiers and
          other diagnostic data.
        </p>

        <p className="text-sm sm:text-base text-gray-700 mb-4">
          We may also collect information that your browser sends whenever you
          visit our Service or when you access the Service by or through a mobile
          device.
        </p>

        <h3 className="text-base sm:text-lg font-semibold mt-6 mb-2">
          Tracking Technologies and Cookies
        </h3>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          We use cookies and similar tracking technologies to track the activity
          on our Service and store certain information. Tracking technologies we
          use include beacons, tags, and scripts to collect and track information
          and to improve and analyze our Service.
        </p>

        <p className="text-sm sm:text-base text-gray-700 mb-3">
          We use both Session and Persistent Cookies for the purposes set out
          below:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base text-gray-700 mb-4">
          <li>
            <span className="font-semibold">Necessary / Essential Cookies</span>
            . These cookies are essential to provide you with services available
            through the Website and to enable you to use some of its features.
          </li>
          <li>
            <span className="font-semibold">
              Cookies Policy / Notice Acceptance Cookies
            </span>
            . These cookies identify if users have accepted the use of cookies on
            the Website.
          </li>
          <li>
            <span className="font-semibold">Functionality Cookies</span>. These
            cookies allow us to remember choices you make when you use the
            Website, such as remembering your login details or language
            preference.
          </li>
        </ul>

        <p className="text-sm sm:text-base text-gray-700 mb-4">
          For more information about the cookies we use and your choices regarding
          cookies, please refer to this Privacy Policy or a separate Cookies
          Policy if provided.
        </p>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Use of Your Personal Data
        </h2>
        <p className="text-sm sm:text-base text-gray-700 mb-3">
          The Company may use personal data for the following purposes:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base text-gray-700 mb-4">
          <li>To provide and maintain the Service.</li>
          <li>
            To manage your account and registration as a user of the Service.
          </li>
          <li>
            For the performance of a contract for products, items or services you
            have purchased or any other contract with us through the Service.
          </li>
          <li>
            To contact you by email, telephone calls, SMS, or other equivalent
            forms of electronic communication regarding updates or informational
            communications related to the Service.
          </li>
          <li>
            To provide you with news, special offers, and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or inquired about,
            unless you have opted not to receive such information.
          </li>
          <li>To attend and manage your requests to us.</li>
          <li>
            For business transfers such as a merger, restructuring, or sale of
            assets in which personal data may be transferred.
          </li>
          <li>
            For other purposes, such as data analysis, identifying usage trends
            and improving our Service, products, services and marketing.
          </li>
        </ul>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Retention of Your Personal Data
        </h2>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          The Company will retain your personal data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your personal data to the extent necessary to comply with
          our legal obligations, resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          The Company will also retain Usage Data for internal analysis purposes.
          Usage Data is generally retained for a shorter period of time, except
          when this data is used to strengthen the security or to improve the
          functionality of our Service, or we are legally obligated to retain this
          data for longer periods.
        </p>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Security of Your Personal Data
        </h2>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          The security of your personal data is important to us, but remember that
          no method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially reasonable
          means to protect your personal data, we cannot guarantee its absolute
          security.
        </p>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Children&apos;s Privacy
        </h2>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone under
          the age of 13. If you are a parent or guardian and you are aware that
          your child has provided us with personal data, please contact us. If we
          become aware that we have collected personal data from anyone under the
          age of 13 without verification of parental consent, we take steps to
          remove that information from our servers.
        </p>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">
          Changes to this Privacy Policy
        </h2>
        <p className="text-sm sm:text-base text-gray-700 mb-4">
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page and
          updating the "Last updated" date at the top of this Privacy Policy.
        </p>

        <h2 className="text-lg sm:text-xl font-semibold mt-6 mb-3">Contact Us</h2>
        <p className="text-sm sm:text-base text-gray-700 mb-1">
          Email: businesskeralagroup@gmail.com
        </p>
        <p className="text-sm sm:text-base text-gray-700 mb-1">
          Website: https://businesskerala.org/
        </p>
        <p className="text-sm sm:text-base text-gray-700 mb-6">
          Phone: +91 75 111 94 200
        </p>
      </div>
    </div>
  );
}

export default PrivacyPage;
